data:
  composer_name: "path_distance"
  context_scopes: ["medium_context", "large_context", "huge_context"]
  data_folder: /mnt/data2/galimzyanov/long-contex-eval/datasets/
  force_prepare: false
model:
  model_name: "deepseek-ai/deepseek-coder-1.3b-base"
eval:
  batch_size: 20
  context_len: 4096 # 16384, 2048